# @package _global_

defaults:
  - robot_base

robot:
  # Observation parameters
  num_bodies: 13
  dof_obs_size: 12
  actions_dim: 12
  policy_obs_dim: -1
  critic_obs_dim: -1

  key_bodies: ["left_ankle_roll_link", "right_ankle_roll_link"]
  contact_bodies: [ "left_ankle_roll_link", "right_ankle_roll_link" ]
  num_feet: 2
  right_foot_name: "right_ankle_roll_link"
  left_foot_name: "left_ankle_roll_link"
  foot_name: "ankle_roll_link"
  knee_name: "knee_link"

  dof_names: ['left_hip_pitch_joint', 'left_hip_roll_joint', 'left_hip_yaw_joint', 'left_knee_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint',
              'right_hip_pitch_joint', 'right_hip_roll_joint', 'right_hip_yaw_joint', 'right_knee_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint']
  upper_dof_names: []
  lower_dof_names: ['left_hip_pitch_joint', 'left_hip_roll_joint', 'left_hip_yaw_joint', 'left_knee_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint',
                    'right_hip_pitch_joint', 'right_hip_roll_joint', 'right_hip_yaw_joint', 'right_knee_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint']
  has_torso: False
  has_upper_body_dof: False
  dof_pos_lower_limit_list: [-2.5307, -0.5236, -2.7576, -0.087267, -0.87267, -0.2618, -2.5307, -2.9671, -2.7576, -0.087267, -0.87267, -0.2618]
  dof_pos_upper_limit_list: [2.8798, 2.9671, 2.7576, 2.8798, 0.5236, 0.2618, 2.8798, 0.5236, 2.7576, 2.8798, 0.5236, 0.2618]
  dof_vel_limit_list: [32.0, 32.0, 32.0, 20.0, 37.0, 37.0, 32.0, 32.0, 32.0, 20.0, 37.0, 37.0]
  dof_effort_limit_list: [88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 88.0, 88.0, 88.0, 139.0, 50.0, 50.0]
  dof_armature_list: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
                      0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
  dof_joint_friction_list: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05,
                            0.05, 0.05, 0.05, 0.05, 0.05, 0.05]


  body_names: ['pelvis', 
                'left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link',
                'right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link']

  terminate_after_contacts_on : ["pelvis", "shoulder", "hip"]
  penalize_contacts_on: ["pelvis", "shoulder", "hip"]
  init_state:
    pos: [0.0, 0.0, 0.8] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles: # = target angles [rad] when action = 0.0
      left_hip_yaw_joint: 0.
      left_hip_roll_joint: 0.
      left_hip_pitch_joint: -0.1
      left_knee_joint: 0.3
      left_ankle_pitch_joint: -0.2
      left_ankle_roll_joint: 0.
      right_hip_yaw_joint: 0.
      right_hip_roll_joint: 0.
      right_hip_pitch_joint: -0.1
      right_knee_joint: 0.3
      right_ankle_pitch_joint: -0.2
      right_ankle_roll_joint: 0.

  randomize_link_body_names: [
    'pelvis', 'left_hip_yaw_link', 'left_hip_roll_link', 'left_hip_pitch_link', 'left_knee_link',
    'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link',
  ]

  motion:
    lower_body_link:
      - "pelvis"
      - "left_hip_pitch_link"
      - "left_hip_roll_link"
      - "left_hip_yaw_link"
      - "left_knee_link"
      - "left_ankle_pitch_link"
      - "left_ankle_roll_link"
      - "right_hip_pitch_link"
      - "right_hip_roll_link"
      - "right_hip_yaw_link"
      - "right_knee_link"
      - "right_ankle_pitch_link"
      - "right_ankle_roll_link"
      - "waist_yaw_link"
      - "waist_roll_link"
      - "torso_link"

    upper_body_link:
      - "left_shoulder_pitch_link"
      - "left_shoulder_roll_link"
      - "left_shoulder_yaw_link"
      - "left_elbow_link"
      - "right_shoulder_pitch_link"
      - "right_shoulder_roll_link"
      - "right_shoulder_yaw_link"
      - "right_elbow_link"
      - "left_hand_link"
      - "right_hand_link"
      - "head_link"


    pelvis_link: "pelvis"
    base_link: "torso_link"
    hips_link:
      - "left_hip_pitch_link"
      - "left_hip_roll_link"
      - "left_hip_yaw_link"
      - "right_hip_pitch_link"
      - "right_hip_roll_link"
      - "right_hip_yaw_link"

  control:
    control_type: P
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      hip_yaw: 100
      hip_roll: 100
      hip_pitch: 100
      knee: 200
      ankle_pitch: 20
      ankle_roll: 20

    damping: # [N*m/rad]  # [N*m*s/rad]
      hip_yaw: 2.5
      hip_roll: 2.5
      hip_pitch: 2.5
      knee: 5.0
      ankle_pitch: 0.2
      ankle_roll: 0.1

    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 0.25
    action_clip_value: 100.0
    clip_torques: True

  asset:
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    urdf_file: "g1/${robot.asset.robot_type}.urdf"
    usd_file: "g1/${robot.asset.robot_type}.usd"
    xml_file: "g1/${robot.asset.robot_type}.xml"
    robot_type: g1_12dof
    self_collisions: 1 # 1 to disable, 0 to enable self collisions
    default_dof_drive_mode: 3

# Override motion lib default to use the adapted H1 variant
# motion_lib:
#   _target_: phys_anim.utils.motion_lib_h1.H1_MotionLib

# Override simulation config to use the adapted H1 variant
# env:
#   config:
#     simulator:
#       sim:
#         fps: 200 # 1/dt , dt = 0.005
#         control_freq_inv: 4  # decimation
#         substeps: 1