# First we define the global structures that will be used by all the configs.
defaults:
  # - base/fabric
  - _self_
  - base/hydra
  - base/structure

# These are global variables that all levels of the config can access.
## Experiment setup
seed: 0
codebase_version: 1.0  # this is recorded to enable auto-conversion of models between different versions of the codebase
headless: True
num_envs: 4096

### Checkpoint logic
auto_load_latest: False
checkpoint: null

### Naming and dir structure
project_name: TEST
experiment_name: TEST

base_dir: logs
timestamp: ${now:%Y%m%d_%H%M%S}
experiment_dir: ${base_dir}/${project_name}/${timestamp}-${experiment_name}-${log_task_name}-${robot.asset.robot_type}
save_dir: ${experiment_dir}/.hydra

force_flat_terrain: False

use_wandb: False
log_task_name: TEST

### Simulation
sim_type: isaacgym
env_spacing: 20
output_dir: ${experiment_dir}/output

eval_overrides:
  headless: False
  num_envs: 1
  auto_load_latest: False
  use_wandb: False
