# @package _global_

# defaults:
#   - reward_base

rewards:
  set_reward: Yuanhang
  set_reward_date: 20250206
  only_positive_rewards: False
  reward_scales:
      tracking_lin_vel: 1.0
      tracking_ang_vel: 0.5
      penalty_lin_vel_z: -2.0
      penalty_ang_vel_xy: -1.0
      penalty_orientation: -1.0
      penalty_torques: -0.00001
      # penalty_dof_vel: -0.0001
      penalty_dof_acc: -3.5e-8
      penalty_action_rate: -0.01
      # penalty_feet_contact_forces: -0.01
      # penalty_stumble: -10.0
      penalty_slippage: -1.0
      penalty_feet_ori: -2.0
      limits_dof_pos: -10.0
      # limits_dof_vel: -5.0
      # limits_torque: -0.1
      feet_air_time: 1.0
      base_height: -10.0
      penalty_feet_height: -2.5
      # termination: -500.0
      # penalty_in_the_air: -100.0
      # feet_max_height_for_this_air: -100.0
      upperbody_joint_angle_freeze: -0.2
      feet_heading_alignment: -0.3
      penalty_close_feet_xy: -10.
      penalty_ang_vel_xy_torso: -1.0
      penalty_hip_pos: -1.0


  reward_tracking_sigma:
    lin_vel: 0.25
    ang_vel: 0.25
  reward_limit:
    soft_dof_pos_limit: 0.9
    soft_dof_vel_limit: 0.9
    soft_torque_limit: 0.9

  feet_height_target: 0.12
  locomotion_max_contact_force: 200.0
  desired_feet_max_height_for_this_air: 0.12
  desired_base_height: 0.78
  close_feet_threshold: 0.15

  reward_penalty_curriculum: False
  reward_initial_penalty_scale : 1.0
  reward_min_penalty_scale: 0.0
  reward_max_penalty_scale: 1.0
  reward_penalty_level_down_threshold: 400
  reward_penalty_level_up_threshold: 700
  reward_penalty_degree: 0.00001
  num_compute_average_epl: 10000

  reward_penalty_reward_names : [
    "penalty_lin_vel_z",
    "penalty_ang_vel_xy",
    "penalty_orientation",
    "penalty_torques",
    "penalty_dof_acc",
    "penalty_dof_vel",
    "penalty_action_rate",
    "penalty_feet_contact_forces",
    "penalty_stumble",
    "penalty_slippage",
    "penalty_feet_ori",
    "penalty_in_the_air",
    "limits_dof_pos",
    "limits_dof_vel",
    "limits_torque",
    "termination",
    "feet_air_time",
    "feet_max_height_for_this_air",
    "penalty_feet_height",
    "upperbody_joint_angle_freeze",
    "penalty_close_feet_xy",
    "penalty_ang_vel_xy_torso",
    "penalty_hip_pos"]

