# @package _global_

domain_rand:
  # push robots
  push_robots : True
  push_interval_s : [5, 10]
  max_push_vel_xy : 1.0

  # base com
  randomize_base_com : True
  base_com_range:
    x : [-0.1., 0.1.]
    y : [-0.1., 0.1.]
    z : [-0.1, 0.1]

  # link mass
  randomize_link_mass : True
  link_mass_range : [0.8, 1.2]

  # pd gain
  randomize_pd_gain : True
  kp_range : [0.75, 1.25]
  kd_range : [0.75, 1.25]

  # friction
  randomize_friction : True
  friction_range : [0.5, 1.25]

  # base mass
  randomize_base_mass : False

  # rfi
  randomize_torque_rfi : True
  rfi_lim : 0.1
  randomize_rfi_lim : True
  rfi_lim_range : [0.5, 1.5]


  # control delay
  randomize_ctrl_delay : True
  ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms